k8s_config:
- manifest_path: /manifests
  cluster_info:
    cluster_id: 4565a845-cdad-57d1-96cd-cdbaee410bc7
    cluster_name: Jaqueline staging
- manifest_path: /manifests
  cluster_info:
    cluster_id: 2b3de145-5563-5781-a7e9-604c3b8a3e79
    cluster_name: Jaqueline's cluster
- manifest_path: /manifests
  cluster_info:
    cluster_id: 4565a845-cdad-57d1-96cd-cdbaee410bc7
    cluster_name: Jaque's cluster
