apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: qotm-mapping-1665611025859
  namespace: default
spec:
  service: qotm.default:80
  timeout_ms: 3000
  connect_timeout_ms: 3000
  retry_policy:
    retry_on: 5xx
    num_retries: 1
    per_try_timeout: 0.150s
  hostname: "*"
  prefix: /
